# Generated by Django 3.0 on 2019-12-10 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='銀行名')),
                ('bank_code', models.CharField(max_length=8, verbose_name='銀行コード')),
            ],
            options={
                'verbose_name': '銀行名',
                'verbose_name_plural': '銀行名',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255, verbose_name='銀行名')),
                ('branch_code', models.CharField(max_length=6, verbose_name='支店コード')),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appv1.Bank')),
            ],
            options={
                'verbose_name': '支店名',
                'verbose_name_plural': '支店名',
            },
        ),
    ]
